#!/usr/bin/env python3
"""Concatenate the VibeLoom UI modules into a single theme.css bundle.
Edit the modules (tokens/base/components/layout/slides), then run this.
    python3 build.py
tokens.css must stay first so its font @import remains valid at the top."""
import pathlib

HERE = pathlib.Path(__file__).parent
ORDER = ["tokens.css", "base.css", "components.css", "layout.css", "slides.css"]

parts = ["/* ============================================================\n"
         "   VibeLoom UI — bundled theme.css  (generated by build.py)\n"
         "   Do not edit directly; edit the modules and re-run build.py.\n"
         "   ============================================================ */"]
missing = []
for f in ORDER:
    p = HERE / f
    if p.exists():
        parts.append(f"\n/* ===================== {f} ===================== */\n"
                     + p.read_text(encoding="utf-8"))
    else:
        missing.append(f)

(HERE / "theme.css").write_text("\n".join(parts), encoding="utf-8")
kb = (HERE / "theme.css").stat().st_size / 1024
print(f"wrote theme.css ({kb:.0f} KB) from {len(ORDER)-len(missing)}/{len(ORDER)} modules")
if missing:
    print("  missing (skipped):", ", ".join(missing))
